export function getPluginLinuxInfo() {
  const linuxPlugin = [
    { name: "apache_status.py", size: "8.89kB" },
    { name: "apache_status_2.py", size: "9.02kB" },
    { name: "asmcmd.sh", size: "523.00B" },
    { name: "db2_mem", size: "787.00B" },
    { name: "dnsclient", size: "1.12kB" },
    { name: "hpux_lunstats", size: "2.04kB" },
    { name: "hpux_statgrab", size: "1.29kB" },
    { name: "ibm_mq", size: "2.83kB" },
    { name: "isc_dhcpd.py", size: "3.24kB" },
    { name: "isc_dhcpd_2.py", size: "3.36kB" },
    { name: "jar_signature", size: "1.37kB" },
    { name: "kaspersky_av", size: "1.18kB" },
    { name: "lnx_quota", size: "954.00B" },
    { name: "lvm", size: "734.00B" },
    { name: "mailman_lists", size: "1.54kB" },
    { name: "mk_apt", size: "1.57kB" },
    { name: "mk_ceph", size: "1.13kB" },
    { name: "mk_cups_queues", size: "1.35kB" },
    { name: "mk_db2.aix", size: "10.36kB" },
    { name: "mk_db2.linux", size: "6.19kB" },
    { name: "mk_docker.py", size: "22.03kB" },
    { name: "mk_docker_2.py", size: "22.20kB" },
    { name: "mk_errpt.aix", size: "2.09kB" },
    { name: "mk_filehandler", size: "588.00B" },
    { name: "mk_filestats.py", size: "19.71kB" },
    { name: "mk_filestats_2.py", size: "19.80kB" },
    { name: "mk_informix", size: "8.55kB" },
    { name: "mk_inotify.py", size: "12.25kB" },
    { name: "mk_inotify_2.py", size: "12.37kB" },
    { name: "mk_inventory.aix", size: "1.80kB" },
    { name: "mk_inventory.linux", size: "4.78kB" },
    { name: "mk_inventory.solaris", size: "2.09kB" },
    { name: "mk_iptables", size: "767.00B" },
    { name: "mk_jolokia.py", size: "22.29kB" },
    { name: "mk_jolokia_2.py", size: "22.46kB" },
    { name: "mk_logins", size: "568.00B" },
    { name: "mk_logwatch.py", size: "42.65kB" },
    { name: "mk_logwatch_2.py", size: "42.75kB" },
    { name: "mk_mongodb.py", size: "25.62kB" },
    { name: "mk_mongodb_2.py", size: "25.74kB" },
    { name: "mk_mysql", size: "2.44kB" },
    { name: "mk_nfsiostat", size: "611.00B" },
    { name: "mk_omreport", size: "592.00B" },
    { name: "mk_oracle", size: "120.54kB" },
    { name: "mk_oracle_crs", size: "4.88kB" },
    { name: "mk_postgres.py", size: " 47.25kB" },
    { name: "mk_postgres_2.py", size: " 47.38kB" },
    { name: "mk_redis", size: "3.15kB" },
    { name: "mk_sap.aix", size: "511.00B" },
  ];

  return linuxPlugin;
}

export function getPluginWidowsInfo() {
  const windowsPlugin = [
    { name: "ad_replication.bat", size: "1.20kB" },
    { name: "arcserve_backup.ps1", size: "5.26kB" },
    { name: "citrix_farm.ps1", size: "7.49kB" },
    { name: "citrix_licenses.vbs", size: "599.00B" },
    { name: "citrix_xenapp.ps1", size: "576.00B" },
    { name: "hyperv_vms.ps1", size: "163.00B" },
    { name: "hyperv_vms_guestinfos.ps1", size: "3.37kB" },
    { name: "iis_app_pool_state.ps1", size: " 586.00B" },
    { name: "kaspersky_av_client.vbs", size: "2.49kB" },
    { name: "mcafee_av_client.bat", size: " 867.00B" },
    { name: "megaraid.bat", size: "2.05kB" },
    { name: "mk_dhcp_enabled.bat", size: "178.00B" },
    { name: "mk_inventory.vbs", size: "13.73kB" },
    { name: "mk_msoffice.ps1", size: "1.18kB" },
    { name: "mk_mysql.vbs", size: " 5.12kB" },
    { name: "mk_oracle.ps1", size: "96.68kB" },
    { name: "msexch_dag.ps1", size: "418.00B" },
    { name: "msexch_database.ps1", size: "535.00B" },
    { name: "mssql.vbs", size: "30.91kB" },
    { name: "netstat_an.bat", size: "127.00B" },
    { name: "rds_licenses.vbs", size: "2.63kB" },
    { name: "rstcli.bat", size: "489.00B" },
    { name: "sansymphony.ps1", size: " 3.74kB" },
    { name: "storcli.bat", size: "426.00B" },
    { name: "tsm_checks.bat", size: " 968.00B" },
    { name: "veeam_backup_status.ps1", size: "5.78kB" },
    { name: "win_dhcp_pools.bat", size: "359.00B" },
    { name: "win_dmidecode.bat", size: " 479.00B" },
    { name: "win_license.bat", size: "201.00B" },
    { name: "win_printers.ps1", size: "1.92kB" },
    { name: "windows_broadcom_bonding.bat", size: "209.00B" },
    { name: "windows_if.ps1", size: "3.88kB" },
    { name: "windows_intel_bonding.bat", size: "439.00B" },
    { name: "windows_multipath.vbs", size: "658.00B" },
    { name: "windows_os_bonding.ps1", size: "943.00B" },
    { name: "windows_tasks.ps1", size: "1.61kB" },
    { name: "windows_updates.vbs", size: "3.67kB" },
    { name: "wmic_if.bat", size: "184.00B" },
  ];

  return windowsPlugin;
}
